### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### exercism/xscheme now has a Chat Room on Gitter

@canweriotnow has just created a chat room. You can visit it here: [https://gitter.im/exercism/xscheme](https://gitter.im/exercism/xscheme?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/exercism/xscheme?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by kytrinyx** [comment]
@canweriotnow I'll let you make the call on this one :)

**Comment by canweriotnow** [comment]
@kytrinyx ah, why not :)

**Comment by canweriotnow** [comment]
Is that new behavior, the auto-PR from Gitter? I think when I first used it I had to copypaste markdown like it was 2013 or something.

**Comment by kytrinyx** [comment]
I've no idea!

**Pull request merged**
