### PR TITLE
Flip the switch

### PR DESCRIPTION
**Pull request by canweriotnow**
Checklist complete, closing #10

### CODE REVIEW

**Comment by canweriotnow** [comment]
@kytrinyx this PR will make the track live, wanted your blessing before merging.

**Comment by kytrinyx** [comment]
Yes! This is awesome. Do you want to soft launch, or should I mention it in the twitters right off the bat?

**Comment by canweriotnow** [comment]
Just fetched, it looks great, tweet away!!!

**Comment by kytrinyx** [comment]
I'll wait until the language listing bug is fixed.

**Comment by canweriotnow** [comment]
Yup, why I haven't mentioned it anywhere. Once that's resolved, I might have to do a blag or something even!

**Comment by kytrinyx** [comment]
A blag!!1! Goodness gracious!

**Pull request merged**
